name: Changelog

on:
  pull_request:
    branches: [master]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'docs: updated CHANGELOG.md'
          add: 'CHANGELOG.md'
          push: origin ${{ steps.extract_branch.outputs.branch }} --set-upstream --force
