name: Changelog

on:
  pull_request:
    types: [ opened ]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog

    steps:
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
