name: Label Checker

on:
  pull_request:
    branches: [master]
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check labels
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch
          none_of: wontfix,duplicate,question
          any_of: documentation,enhancement,bug
          repo_token: ${{ secrets.GITHUB_TOKEN }}
