name: Lint

on:
  pull_request:
    branches: [master]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint
