name: Vercel Production Deployment

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  NEON_DATABASE_USERNAME: ${{ secrets.NEON_DATABASE_USERNAME }}
  NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  release:
    types:
      - created

jobs:
  create_production_deployment:
    permissions: write-all
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ steps.seturl.outputs.url }}

    steps:
      - uses: actions/checkout@v3

      - name: Run Prisma Migrate
        run: |
          npx prisma generate
          npx prisma migrate deploy

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }} >deployment-url.txt

      - name: Set Production URL
        run: echo "url=$(cat deployment-url.txt)">> $GITHUB_OUTPUT
        id: seturl
