name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  release:
    types:
      - created

jobs:
  create_deployment:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ steps.seturl.outputs.url }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Set Production URL
        run: echo "url=$(tail -1 deploy.log)">> $GITHUB_OUTPUT
        id: seturl

      - name: Log Production URL
        run: echo "${{ steps.seturl.outputs.url }}"
